repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        stages: [commit, merge-commit, push, manual]
      - id: check-case-conflict
        stages: [commit, merge-commit, push, manual]
      - id: check-json
        stages: [commit, merge-commit, push, manual]
      - id: check-merge-conflict
        stages: [commit, merge-commit, push, manual]
      - id: check-symlinks
        exclude: CMakeLists.txt
        stages: [commit, merge-commit, push, manual]
      - id: check-toml
        stages: [commit, merge-commit, push, manual]
      - id: check-xml
        files: '.*\.(xml|launch)'
        stages: [commit, merge-commit, push, manual]
      - id: check-yaml
        stages: [commit, merge-commit, push, manual]
      - id: debug-statements
        stages: [commit, merge-commit, push, manual]
      - id: destroyed-symlinks
        exclude: CMakeLists.txt
        stages: [commit, merge-commit, push, manual]
      - id: detect-private-key
        stages: [commit, merge-commit, push, manual]
      - id: end-of-file-fixer
        stages: [commit, merge-commit, push, manual]
      - id: mixed-line-ending
        stages: [commit, merge-commit, push, manual]
      - id: trailing-whitespace
        stages: [commit, merge-commit, push, manual]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        stages: [commit, merge-commit, push, manual]
        additional_dependencies:
          - prettier
          - "@prettier/plugin-xml"

  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        stages: [commit, merge-commit, push, manual]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        args: ["--write-changes", "--ignore-words=.codespell_words"]
        exclude: CHANGELOG.rst
        stages: [commit, merge-commit, push, manual]
